In [1]:
"""
Running this cell takes some time the first time, because the Numba JIT compilaton that compiles some 
"""

from Py3DViewer import Trimesh, Quadmesh, Tetmesh, Hexmesh
from Py3DViewer import Viewer, laplacian_smoothing
from Py3DViewer import AABB, Triangle
import numpy as np

In [2]:
triangle = Triangle([[-1,-1,-1],[2,2,2],[2,2,2]],[[-1,-1,-1],[2,2,2]])
triangle.print()

aabb = AABB([[-1,-1,-1],[2,2,2]])
aabb2 = AABB([[0,0,0],[1,1,1]])
aabb.centre_point()



aabb.contains([2,3,4])
aabb.intersect_box(aabb2)


[[-1 -1 -1]
 [ 2  2  2]
 [ 2  2  2]]
[[-1 -1 -1]
 [ 2  2  2]]
[[-1 -1 -1]
 [ 2  2  2]]
[[0 0 0]
 [1 1 1]]


True

In [ ]:
mesh = [Trimesh('data/bunny_tris.obj'), Quadmesh('data/bunny_quad.obj')]

In [ ]:
"""
After running this cell, you will notice that the quad bunny is quite larger than the tri bunny,
and is also oriented differently.
"""
viewer = Viewer(mesh, width=1000, height=300)
viewer.show()

In [ ]:
"""
Let's first scale the meshes to have a bounding box diagonal of 10, then update the viewer. 
NOTE: The viewer update takes some time depending
on the quality of your connect, since the new geometry is streamed from the backend to your browser.
"""

mesh[0].vertices /= np.linalg.norm(mesh[0].bbox[1]-mesh[0].bbox[0])
mesh[0].vertices *= 10
mesh[1].vertices /= np.linalg.norm(mesh[1].bbox[1]-mesh[1].bbox[0])
mesh[1].vertices *=10
viewer.update_controls()
viewer.update()

In [ ]:
"""
Let's rotate the quad bunny by using the transform_rotation method
"""
mesh[1].transform_rotation(-90, 'x')
viewer.update()

In [ ]:
"""
Let's now do the same with a "reactive" approach.
When using a reactive viewer, the user can simply act on the mesh data however they choose, and the viewer
is asynchronously updated (with a minimal, if any, overhead on the computation).

Again, consider that the redraws are strongly bound by the fact that the Python and Javascript backend are
de-coupled in this context, since Binder runs in the cloud. We highly suggest trying the library locally to
properly experience the reactive redraws.
"""
mesh2 = [Trimesh('data/bunny_tris.obj'), Quadmesh('data/bunny_quad.obj')]
viewer2 = Viewer(mesh2, width=1000, height=500, reactive=True)
viewer2.show()

In [ ]:
mesh2[0].vertices /= np.linalg.norm(mesh2[0].bbox[1]-mesh2[0].bbox[0])
mesh2[0].vertices *= 10
mesh2[1].vertices /= np.linalg.norm(mesh2[1].bbox[1]-mesh2[1].bbox[0])
mesh2[1].vertices *=10
viewer2.update_controls()
mesh2[1].transform_rotation(-90, 'x')

In [ ]:
"""
Here's an example with the GUI, which only works with a single mesh per scene so far. We are working to support multiple meshes.
"""
mesh3 = Hexmesh('data/double_hinge_hex.mesh')
viewer3 = Viewer(mesh3, width=1000, height=300, with_gui=True)
viewer3.show()

In [ ]:
"""
Py3DViewer have texture support for surface meshes.
These are some examples.
"""
spot = Trimesh('data/spot.obj', texture='data/textures/spot_texture.png')
blub = Trimesh('data/blub.obj', texture='data/textures/blub_texture.png')
cube_tris = Trimesh('data/cube_tris_mtl.obj', mtl='data/cube.mtl')
cube_quad = Quadmesh('data/cube_quad_mtl.obj', mtl='data/cube.mtl')
spot.show()
blub.show()
cube_tris.show()
cube_quad.show()